config/routes.rb
Rails.application.routes.draw do
  post 'kakutan_pdfs/index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  root :to => 'tops#home'
  get "quiz" => "tops#quiz"
  get "toeic" => "tops#toeic"
  post "search" => "tops#search"
  get "novel" => "tops#novel"
  get "paper" => "tops#paper"
  get "type" => "tops#type"
  get "kakutan" => "tops#kakutan"
  get "select" => "tops#select"
  get "about" => "tops#about"

  post 'results' => "results#create"
  post "kakutan" => "tops#kakutan"
  post 'type/results' => "results#create_type"
  post 'word/json' => "word_sets#create"
  post 'translation' =>"translations#count"
  post "user" => "users#update"


  get '*path', controller: 'application', action: 'render_404'
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def home
  end

  def about
  end

  def quiz
    quiz_level = params[:level]
    user_id = current_user ? current_user.id : nil
    @test = ["level" => quiz_level,"quiz_file"=> params[:select_file], "user_id"=>user_id] if params[:test]
    gon.test = @test
    # 単語の選択
    gon.questions = Quiz.select_question_type(params[:select_num], params[:quiz_type], params[:select_file])
  end

  def select
    gon.user_level_array = current_user ? {"toeic"=>current_user.toeic_status,"novel"=>current_user.novel_status,"paper"=>current_user.paper_status} : 0
  end


  def toeic
    @list =Fileloader.reader(0)
    @number =0
  end

  def paper
    @list =Fileloader.reader(1)
    @number =1
  end

  def novel
    @list =Fileloader.reader(2)
    @number =2
  end

  def search
    if params[:search].present?
        @list =Fileloader.reads(params[:search],params[:number],params[:model])
    end
  end

  def kakutan
    @word_sets = Fileloader.pdf_words(params[:select_num], params[:word_range], params[:select_file])
    @select_num_array = ['', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    @selected_num = ''
  end

  def type
    select_file = params[:select_file].to_i
    select_num = params[:select_num].to_i
    quiz_type = params[:quiz_type].to_i
    if select_num != 0
      if quiz_type == 0
        gon.questions = Quiz.type(select_num, select_num+99, select_file)
      elsif quiz_type == 1
        gon.questions = Quiz.type(select_num, select_num+499, select_file)
      elsif quiz_type == 2
        gon.questions = Quiz.type(select_num, select_num+999, select_file)
      elsif quiz_type == 3
        gon.questions = Quiz.type(2, 2001, select_file)
      else
        gon.questions = Quiz.type(2, 2001, select_file)
      end
    else
      gon.questions = Quiz.type(2, 2001, select_file)
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/_form.html.erb
<div class="form">
  <%= form_with(url: search_path,method: :post) do |f| %>
  <%= f.text_field :search ,id:"search"%>
  <%= f.select :model , options_for_select({"英語": :english,"日本語": :japan})%>
  <%= f.hidden_field :number ,value: number %>
  <%= f.submit 'Search',id:"submit_bottan"%>
  <% end %>
</div>

app/views/tops/_tabledic.html.erb
<table class="table">
  <thead>
    <tr>
      <th>順位</th>
      <th>単語</th>
      <th>意味</th>
      <th>例文</th>
    </tr>
  </thead>
  <tbody>
    <% list.each do |row| %>
    <tr>
      <% for i in 0..3 %>
      <td><%= row[i] %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tops/_translation.html.erb
<div id="submit">
	<%= trans_num %>回変更
</div>

app/views/tops/about.html.erb
<div id="about">
  <div class="container-fluid mt-5">
    <div class="starter-template">
      <h3>プライベートポリシー</h3>
      <p>本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，利用者の個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>

      <h4>第1条（個人情報）</h4>
      <p>「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報を指します。</p>

      <h4>第2条（個人情報の収集方法）</h4>
      <p>利用者が利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，クレジットカード番号などの個人情報をお尋ねすることがあります。</p>

      <h4>第3条（個人情報を収集・利用する目的）</h4>
      <p>個人情報を収集・利用する目的は，以下のとおりです。</p>
      <p>1. サービスの提供・運営のため
      2. 利用者からのお問い合わせに回答するため（本人確認を行うことを含む）<br>
      3. 利用者が利用中のサービスの新機能，更新情報，キャンペーン等及び他のサービスの案内のメールを送付するため<br>
      4. メンテナンス，重要なお知らせなど必要に応じたご連絡のため<br>
      5. 利用規約に違反した利用者や，不正・不当な目的でサービスを利用しようとする利用者の特定をし，ご利用をお断りするため<br>
      6. 利用者にご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため<br>
      7. 有料サービスにおいて，利用者に利用料金を請求するため<br>
      8. 上記の利用目的に付随する目的</p>

      <h4>第4条（利用目的の変更）</h4>
      <p>1. 利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。<br>
      2. 利用目的の変更を行った場合には，変更後の目的について，所定の方法により，利用者に通知し，または本ウェブサイト上に公表するものとします。</p>

      <h4>第5条（プライバシーポリシーの変更）</h4>
      <p>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，利用者に通知することなく，変更することができるものとします。</p>

      <h4>第6条（お問い合わせ窓口）</h4>
      <p>本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。</p>
      <a href="https://docs.google.com/forms/d/e/1FAIpQLScTmp7v8SXMrrBtQhV08EJbSA1HSgtt6dZcm1vdDZIpoeGBiQ/viewform">お問い合わせフォーム</a>

      <p>以上</p>
    </div>
  </div>
</div>

<script>
  $('nav').addClass("bg-dark");
  $('nav').removeClass("fixed-top");
</script>
<style>

</style>

app/views/tops/home.html.erb
<section id="main-visual" class="text-center">
  <div class="box">
    <div class="bgImg src1"></div>
    <div class="bgImg src2"></div>
    <div class="bgImg src3"></div>
    <div class="bgImg src4"></div>
    <div class="boxString">
      <div class="align-self-center mainv-fade get-started gs1">
        <h1 class="pb-2">あなたにはあなたに合う、英語がある</h1>
        <a href="/select" class="btn btn-flat2"><span>Get started</span></a>
      </div>
    </div>
  </div>
</section>
<div class="container-fluid">
  <div class="pt-6 text-center">
    <h4>どうしても英単語が覚えられなくて悩んでいる方<br>そんなあなたのためにご用意いたしました</h4>
  </div>
  <section id="main-content" class="mt-5">
    <div class="text-center fadein">
      <h2 class="text-center my-h1">勉強方法</h2>
    </div>
    <div id="main-content1" class="row py-6 fadein">
      <div class="col-sm-6 align-self-center">
        <div class="frame">
          <img src="assets/images/4-quiz.png" width="100%" height="100%" alt="画像">
        </div>
      </div>
      <div class="col-sm-6 align-self-center text-left">
        <div class="box-line">
          <h2>4択クイズ</h2>
          <p class="">選択肢の中から出題される英語の意味だと思うものを選んでみましょう<br>問題数を10問、30問、100問から選べるので自分の時間に合わせて問題数を選んでみましょう<br>この問題をやり切れば英単語が出された瞬間にその意味を答えれるようになるかも？！</p>
        </div>
      </div>
    </div>
    <div id="main-content2" class="row py-6 fadein">
      <div class="col-sm-6 order-sm-2 align-self-center">
        <div class="frame">
          <img src="assets/images/typing.png" width="100%" height="100%" alt="画像">
        </div>
      </div>
      <div class="col-sm-6 order-sm-1 align-self-center text-left">
        <div class="box-line">
          <h2>タイピングテスト</h2>
          <p>出された日本語に対応する英語を答えましょう<br>英語から日本語よりも逆の方が難しいうえに一つでもスペルを間違えると×になってしまうため難易度はとんでもなく高いです<br>これを全問正解できればあなたはもう単語マスターと言っても過言ではないでしょう</p>
        </div>
      </div>
    </div>
    <div id="main-content3" class="row py-6 fadein">
      <div class="col-sm-6 align-self-center">
        <div class="frame">
          <img src="assets/images/pdf.png" width="100%" height="100%" alt="画像">
        </div>
      </div>
      <div class="col-sm-6 align-self-center text-left">
        <div class="box-line">
          <h2>pdf印刷</h2>
          <p>自分だけの英単語問題集をpdfでダウンロードすることができ、英単語を書いて覚えたい人にとっては欠かせないモードになります<br>最大10枚ずつすることができ、一度にたくさん印刷したいというニーズにも答えられるように設計しました<br>和英、英和どちらのテストもできるためどのように問題を出されても対応できるようになるでしょう</p>
        </div>
      </div>
    </div>
  </section>
  <section id="explanation" class="my-3">
    <div class="text-center fadein">
      <h2 class="text-center my-5 my-h1">仕様技術</h2>
    </div>
    <div class="row my-5 fadein">
      <div class="col-sm-3 align-self-center">
        <div class="frame">
          <img src="assets/images/kikaigakusyu.png" width="100%" height="100%" alt="画像">
        </div>
      </div>
      <div class="col-sm-9 align-self-center">
        <div class="box-line">
          <h2>機械学習について</h2>
          <p>単語はTFIDF法により出現頻度と希少度の項目から重要度を算出しています
            小説と論文の2種類で重要度順に並べる方法を採用しており、それらを読む際に必要になるであろう単語の知識を効率的に学ぶことができます。</p>
        </div>
      </div>
    </div>
    <div class="row my-5  fadein">
      <div class="col-sm-3 align-self-center">
        <div class="frame">
          <img src="assets/images/select.png" width="100%" height="100%" alt="画像">
        </div>
      </div>
      <div class="col-sm-9 align-self-center">
        <div class="box-line">
          <h2>単語集が選択可能</h2>
          <p>E-TANでは他の英単語アプリではあまり見られないディレクトリ構造を採用したアプリケーションとなっています<br>TOEIC、論文の単語などその時に学習したい英単語を選択肢の中から選ぶことができます</p>
        </div>
      </div>
    </div>
    <div class="row my-5  fadein">
      <div class="col-sm-3 align-self-center">
        <div class="frame ">
          <img src="assets/images/test.png" width="100%" height="100%" alt="画像">
        </div>
      </div>
      <div class="col-sm-9 align-self-center">
        <div class="box-line">
          <h2>進級テストによるモチベーション</h2>
          <p>4択テスト、タイピングテストにはそれぞれ進級テストというものが存在します<br>自分が学習しきったと思ったらその範囲の進級テストを受けてみましょう！<br>進級テストは90%以上とらないと合格できないという厳しい条件ではありますが合格するとマイページに自分の進捗として記載されるので進捗100%を目指してどんどん問題を解いていきましょう！</p>
        </div>
      </div>
    </div>
  </section>
  <section id="get-started" class="get-started text-center mb-5 fadein">
    <a href="/select" class="btn btn-flat2"><span>Get started</span></a>
  </section>
</div>
<%= render :partial => "layouts/footer" %>

<style>
  .container-fluid {
    padding-left: 5%;
    padding-right: 5%;
  }
</style>
<script>
  // $('nav').removeClass('fixed-top');
  // $('nav').addClass("bg-dark");

  $('.mainv-fade').hide().fadeIn(5000);

  $(window).scroll(function() {
    $('.fadein').each(function() {
      var elemPos = $(this).offset().top,
        scroll = $(window).scrollTop(),
        windowHeight = $(window).height();
      if (scroll > elemPos - windowHeight + 100) {
        $(this).addClass('scrollin');
      }
    });
  });
</script>

app/views/tops/kakutan.html.erb
<div class="container-fluid pt-6 top-kakutan">
	<div class="row">
		<div class="col-xl-1">
		</div>
		<div class="col-xl-7">
			<div class="tab-content overflow" id="blockquotes-tabContent">
				<% for i in 1..10 do %>
				    <% if i == 1 %>
					    <div class="tab-pane show active" id="blockquotes-1" role="tabpanel" aria-labelledby="blockquotes-tab-1">
						  <table id="table" class="table table-striped", border="2">
							<thead>
								<tr>
									<th class="th_first" style="width:25%;">英語</th>
									<th class="th_second" style="width:25%;">日本語</th>
									<th class="th_first" style="width:25%;">英語</th>
									<th class="th_second" style="width:25%;">日本語</th>
								</tr>
							</thead>
							<tbody>
								<% for j in 0..24 do %>
									<tr>
									    <td class="td_first"><%= @word_sets[j*2][0] %></td>
										<td class="td_second"><%= @word_sets[j*2][1] %></td>
										<td class="td_first"><%= @word_sets[j*2+1][0] %></td>
										<td class="td_second"><%= @word_sets[j*2+1][1] %></td>
									</tr>
								<% end %>
							</tbody>
						  </table>
						</div>
					<% else %>
						<div class="tab-pane " id="blockquotes-<%= i.to_s %>" role="tabpanel" aria-labelledby="blockquotes-tab-<%= i.to_s %>">
						  <div class="tab-pane show active" id="blockquotes-1" role="tabpanel" aria-labelledby="blockquotes-tab-1">
							  <table id="table" class="table table-striped", border="2">
								<thead>
									<tr>
										<th class="th_first" style="width:25%;">英語</th>
										<th class="th_second" style="width:25%;">日本語</th>
										<th class="th_first" style="width:25%;">英語</th>
										<th class="th_second" style="width:25%;">日本語</th>
									</tr>
								</thead>
								<tbody>
									<% for j in 0..24 do %>
										<tr>
										    <td class="td_first"><%= @word_sets[j*2+(i-1)*25][0] %></td>
											<td class="td_second"><%= @word_sets[j*2+(i-1)*25][1] %></td>
											<td class="td_first"><%= @word_sets[j*2+1+(i-1)*25][0] %></td>
											<td class="td_second"><%= @word_sets[j*2+1+(i-1)*25][1] %></td>
										</tr>
									<% end %>
								</tbody>
							  </table>
						  </div>
					    </div>
					<% end %>
				<% end %>
			</div>
	    </div>

		<div class="col-xl-3">
	        <%= form_with url: kakutan_pdfs_index_path(format: "pdf"), local: true do |f| %>
			    <% for i in 1..10 %>
				    <% for j in 0+(i-1)*25..24+(i-1)*25 do %>
						<%= f.hidden_field "word_set[words][][english_first]", :value => @word_sets[j*2][0] %>
						<%= f.hidden_field "word_set[words][][japanese_first]", :value => @word_sets[j*2][1] %>
						<%= f.hidden_field "word_set[words][][english_second]", :value => @word_sets[j*2+1][0] %>
						<%= f.hidden_field "word_set[words][][japanese_second]", :value => @word_sets[j*2+1][1] %>
					<% end %>
				<% end %>
				<div class="cp_ipselect">
					<div>
					    <%= f.select :select_num, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], {include_blank: "pdf印刷の枚数を選んでください"}, {class: "cp_sl06"} %>
					</div>
					<span class="cp_sl06_highlight"></span>
					<span class="cp_sl06_selectbar"></span>
				</div>
			    <%= f.hidden_field :post_trans_num, :id => 'post_trans_num' %>
				<%= button_tag :type => "submit", :class =>"btn btn-flat", :id =>"submit" do %>
				  <span>PDF表示</span>
				<% end %>
				<div>
				    <button id="change" type="button" class="btn btn-flat"><span>和英変換</span></button>
				</div>
				<div>
				    <button id="shuffle" type="button" class="btn btn-flat"><span>シャッフル</span></button>
			    </div>
			<% end %>
			<div class="page">ページ</div>
			<ul class="nav nav-pills mx-auto justify-content-around navbar-light" id="blockquotes-tab" role="tablist">
		   	 <% for i in 1..10 do %>
		   	     <% if i == 1 %>
			       <li class="nav-item">
			         <a class="nav-link active" id="blockquotes-tab-1" data-toggle="pill" href="#blockquotes-1" role="tab" aria-controls="blockquotes-left-1" aria-selected="true">
				         <%= i %>
				     </a>
			       </li>
				 <% else %>
				   <li class="nav-item">
			         <a class="nav-link" id="blockquotes-tab-<%= i %>" data-toggle="pill" href="#blockquotes-<%= i %>" role="tab" aria-controls="blockquotes-<%= i %>" aria-selected="false">
				         <%= i %>
				     </a>
				   </li>
				 <% end %>
			 <% end %>
		    </ul>
		</div>
		<div class="col-xl-1"></div>
	</div>
</div>

<script>
{
	const change = document.getElementById("change")
	const th_first = document.getElementsByClassName('th_first');
	const th_second = document.getElementsByClassName('th_second');
	const td_first = document.getElementsByClassName('td_first');
	const td_second = document.getElementsByClassName('td_second');
	const submit = document.getElementById('submit');
	let trans_num = 0;

	change.addEventListener("click", function () {
	  let tmp_th;
	  let tmp_td;
	  let post_trans_num = document.getElementById("post_trans_num")

	  for (let i = 0; i < th_first.length; i++) {
	  	tmp_th = th_first[i].textContent;
	    th_first[i].textContent = th_second[i].textContent;
	    th_second[i].textContent = tmp_th;
	  }

	  for (let i = 0; i < td_first.length; i++) {
	    tmp_td = td_first[i].textContent
	    td_first[i].textContent = td_second[i].textContent;
	    td_second[i].textContent = tmp_td;
	  }

	  trans_num += 1
	  $.ajax({
	      type: 'POST',
	      url: '/translation',
	      data: {
                    trans_num: trans_num
                },
	  });
      post_trans_num.value = trans_num
	  return trans_num;
    })

    const select = document.getElementById('select_num');

	select.onchange = function(page_num){
	  page_num = this.value
	  $.ajax({
	      type: 'POST',
	      url: '/kakutan',
	      data: {
                    select_num: page_num
                },
	  });
	  return page_num
	}

	const shuffle = document.getElementById('shuffle');

    shuffle.addEventListener('click', function () {
        doReload();
	});

	function doReload() {
	    window.location.reload();
	}

}
</script>

app/views/tops/novel.html.erb
<div class="container-fluid top_s">
  <%= render 'tops/form', number: @number %>
  <div class="detail__table">
    <%= render 'tops/tabledic', list: @list %>
  </div>
</div>

<script>
  $('nav').addClass("bg-dark");
</script>

app/views/tops/paper.html.erb
<div class="container-fluid top_s">
  <%= render 'tops/form', number: @number %>
  <div class="detail__table">
    <%= render 'tops/tabledic', list: @list %>
  </div>
</div>

<script>
  $('nav').addClass("bg-dark");
</script>

app/views/tops/search.js.erb
$('#search').val('')
$('.detail__table').html("<%= j(render 'tops/tabledic', list: @list) %>")

app/views/tops/toeic.html.erb
<div class="top_s">
<div class="container-fluid mt-5">
  <%= render 'tops/form', number: @number %>
  <div class="detail__table">
    <%= render 'tops/tabledic', list: @list %>
  </div>
</div>
</div>
<script>
  $('nav').addClass("bg-dark");
</script>

app/views/tops/type.html.erb
  <div class="container-fluid top-type">
    <p id="text" class="top-var">typing question</p>
    <%# <input type="text" name="name"> %>
    <%# <input type="text" id="targ" name="target" value="" style="display: block; margin: 0 auto; color: rgb(0, 0, 0);"> %>
    <p id="target"></p>
    <div class="row row1_1">
      <div class="col-4">
        <a id="target1" class="btn btn-rounded bottan">10問</a>　
      </div>
      <div class="col-4">
        <a id="target2" class="btn btn-rounded bottan">20問</a>　
      </div>
      <div class="col-4">   
        <a id="target3" class="btn btn-rounded bottan">30問</a>　
      </div>
    </div>
    <div class="row row1_2">
      <p id="botan"> </p>
    </div>
    <div class="row row1_3">
      <strong id="info">
      正解問題数: <span id="score" class="number">0</span>
      残り問題数: <span id="total" class="number">0</span>
      問題数: <span id="time" class="number">0</span>
      </strong>
    </div>
    <div id="cla" class="container-fluid mx-auto text-center answer">
      <div id="row1_4"class="row">
        <div class=col-sm-6>
          <table class='data-table table table-borderd table-striped thead-dark'style="color:black;">
            <tr><th id="good" colspan="2"></th></tr>
            <tr><td>英語</td><td>日本語</td></tr>
          </table>
        </div>
        <div class=col-sm-6>
          <table class="data-table table table-borderd"style="color:black;">
            <tr><th id="missing"colspan="2"></th></tr>
            <tr><td>英語</td><td>日本語</td></tr>
          </table>
        </div>
      </div>
    </div>
  </div>


<script>
{
  const words = gon.questions;
  let word;
  let cnt;
  let loc;
  let score;
  let miss;
  let plusword;
  let apple;
  let Playing = false;

  let total_count;
  let list;
  const target = document.getElementById('target');
  // const targ = document.getElementById('targ');
  const target1 = document.getElementById('target1');
  const target2 = document.getElementById('target2');
  const target3 = document.getElementById('target3');
  const text = document.getElementById('text');
  const time = document.getElementById('time');

  const scoreLabel = document.getElementById('score');
  const missLabel = document.getElementById('miss');

  const total = document.getElementById("total")

  const table = document.getElementById('tab');
  const answer = document.getElementById('answer');

  let tables= document.getElementsByClassName('data-table');
  const good = document.getElementById('good');
  const mi = document.getElementById('missing');
  // const ro1 = document.getElementById('row1_1');
  // const ro2 = document.getElementById('row1_2');
  // const ro3 = document.getElementById('row1_3');

  // 現在の display プロパティの値を保持
  const displayOriginal = tables[0].style.display;
  const displayOrigina = tables[1].style.display;
  // const displayOrigin = targ.style.display;
// none に設定して非表示
  tables[0].style.display = 'none';
  tables[1].style.display = 'none';
  // targ.style.display ="none"
  function tr_create(wor,x) {
    for (var i = 0; i < wor.length; i++) {
    var tr = document.createElement('tr');
    for (var j = 0; j < 2; j++) {
      var td = document.createElement('td');
    // テーブルの列を 2行追加する
    if (j===0) {
      td.innerHTML = wor[i][0];
    }
    else if(j===1){
      td.innerHTML = wor[i][1];
    }
    tr.appendChild(td);
  }
  tables[x].appendChild(tr);
  }
  }

  function updateTarget() {
    let placeholder ="";
    for (let i = cnt; i > 0; i--) {
      placeholder += '_';
    }
    text.textContent = word[1]
    target.textContent = plusword + placeholder ;
    // if (placeholder.length==word[0].length){
    //   $('#targ').val('');
    // }
  }

  function for_base(para) {
    let loc=[];
    for(let i= 0;i<para.length;i++){
      loc.push(para[i])
    }
    return loc
  }
  function updateTimer() {

    if (total_count <= 0) {
      Playing = true;

      target.textContent = 'F I N I S H';
      total.textContent = total_count;
      text.textContent ="";
      good.textContent ="正解問題"
      mi.textContent ="不正解問題"
      removebotan()
      gameEnd()
      // 元に戻して表示
      tables[0].style.display = displayOriginal;
      tables[1].style.display = displayOriginal;
      // targ.style.display ="none"
      tr_create(for_base(apple),0)
      tr_create(for_base(list),1)
      // const ro1 = document.getElementsByClassName('row1_1');
      // const ro2 = document.getElementsByClassName('row1_2');
      // const ro3 = document.getElementsByClassName('row1_3');
      // ro1.setAttribute("id","row_all1");
      // ro2.setAttribute("id","row_all2");
      // ro3.setAttribute("id","row_all3");

    }
  }
  function createbotan(parama) {
    botans =document.getElementById("botan");
    if (botans.hasChildNodes()){
      const input = document.createElement("input");
      input.setAttribute("type","button");
		  input.setAttribute("size","50");
      input.setAttribute("id",parama)
		  input.setAttribute("value",parama);
      botans.appendChild(input);
    }
  }
  function removebotan() {
    const botan = document.getElementById("botan");
	  if (botan.hasChildNodes()){
		while (botan.firstChild) {
      botan.removeChild(botan.firstChild);
    }
  }}

  function plus(lists,word) {
    lists.push(word)
  }

  function gameEnd() {
    let appai =[]
    let miss =[]
    for (let i=0;i<apple.length;i++){
       appai =apple[i]
      $.ajax({
        url: '/type/results',
        type: 'POST',
        data: {
          results: appai
        }
      })
    }
    for (let i=0;i<list.length;i++){
       miss =list[i]
      $.ajax({
        url: '/type/results',
        type: 'POST',
        data: {
          miss: miss
        }
      })
    }

  }
  function starts() {
    if (Playing === true) {
      return;
    }
    Playing = true;

    createbotan("next")
    createbotan("reset")
    // targ.style.display = displayOrigin;
    loc = 0;
    score = 0;
    miss = 0;
    cnt =0;
    total_count=this.name
    plusword ="";
    apple =[]
    list =[]
    scoreLabel.textContent = score;
    word = words[Math.floor(Math.random() * words.length)];
    time.textContent =this.name
    total.textContent = total_count;
    cnt =word[0].length;
    target1.style.display ="none";
    target2.style.display ="none";
    target3.style.display ="none";
    updateTarget()
    if (Playing!==false){

    if (!next.hasChildNodes()){
          next.addEventListener("click", function (e) {
            plus(list,word)
            // $('#targ').val('');
            word = words[Math.floor(Math.random() * words.length)];
            total_count --;
            total.textContent = total_count;
            cnt =word[0].length;
            loc =0;
            plusword ="";
            updateTarget();
            updateTimer();
        })
     }
    }
    if (!reset.hasChildNodes()){
      reset.addEventListener("click", function (e) {
        text.textContent ="";
        target.textContent=""
        alert("処理が終了されますがよろしいですか");
        window.location.reload();
      })
    }
  }

      target1.addEventListener("click", {
        name: 10, handleEvent: starts
      }, false);
      target2.addEventListener("click", {
        name: 20, handleEvent: starts
      }, false);
      target3.addEventListener("click", {
        name: 30, handleEvent: starts
      }, false);

  window.addEventListener('keydown', e => {
    if (Playing !== true) {

      return;
    }
    if (e.key === word[0][loc]) {
      loc++;
      cnt --;
      plusword +=word[0][loc-1]
      if (loc === word[0].length) {
        plus(apple,word)
        word = words[Math.floor(Math.random() * words.length)];
        total_count --;
        total.textContent = total_count;

        loc = 0;
        cnt = word[0].length;
        plusword ="";
        score++;
        scoreLabel.textContent = score;
      }
      updateTarget();
      updateTimer()
    }
  });

}
</script>

<style>
#cla>.row{
  height: auto;
}
</style>