config/routes.rb
Rails.application.routes.draw do
  post 'kakutan_pdfs/index'
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  root :to => 'tops#home'
  get "quiz" => "tops#quiz"
  get "toeic" => "tops#toeic"
  post "search" => "tops#search"
  get "novel" => "tops#novel"
  get "paper" => "tops#paper"
  get "type" => "tops#type"
  get "kakutan" => "tops#kakutan"
  get "select" => "tops#select"
  get "about" => "tops#about"

  post 'results' => "results#create"
  post "kakutan" => "tops#kakutan"
  post 'type/results' => "results#create_type"
  post 'word/json' => "word_sets#create"
  post 'translation' =>"translations#count"
  post "user" => "users#update"


  get '*path', controller: 'application', action: 'render_404'
end

app/views/layouts/_footer.html.erb
<footer id="home-footer" class="bg-dark">
  <div class="container-footer">
    <div class="row">

      <div class="col-md-4 col-sm-6 col-xs-12">
        <span class="logo">
          E-tan
        </span>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="menu">
          <span>Menu</span>
          <li>
            <a href="/">Home</a>
          </li>

          <li>
            <a href="/select">Select Mode</a>
          </li>

          <li>
            <%= link_to "Sign up" , new_user_registration_path %>
          </li>

          <li>
            <%= link_to "Login" , new_user_session_path %>
          </li>
        </ul>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="address">
          <span>Contact</span>
          <li>
            <a href="https://docs.google.com/forms/d/e/1FAIpQLScTmp7v8SXMrrBtQhV08EJbSA1HSgtt6dZcm1vdDZIpoeGBiQ/viewform">お問い合わせ</a>
          </li>
          <li>
            <a href="/about">利用規約</a>
          </li>
        </ul>
      </div>


    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header role="header">
  <!-- Navbar -->
  <nav class="js-navbar-scroll navbar navbar-expand-lg navbar-transparent navbar-dark fixed-top">
    <div class="container-fluid">
      <%= link_to root_path , class: " navbar-brand" do %>
      <h2>E-tan</h2>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo" aria-controls="navbarTogglerDemo" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to root_path, class: "nav-link" do %>
            <i class="fas fa-cubes u-font-size-90 mr-1"></i>
            Home
            <% end %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to select_path, class: "nav-link" do %>
            <i class="fas fa-cube u-font-size-90 mr-1"></i>
            select
            <% end %>
          </li>
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to user_path(current_user), class: "nav-link" do %>
            <i class="fas fa-cube u-font-size-90 mr-1"></i>
            My Page
            <% end %>
          </li>
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to "Logout" , destroy_user_session_path, method: :delete,  class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to select_path, class: "nav-link" do %>
            <i class="fas fa-cube u-font-size-90 mr-1"></i>
            select
            <% end %>
          </li>
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to "Sign up" , new_user_registration_path,  class: "nav-link" %>
          </li>
          <li class="nav-item mr-4 mb-lg-0">
            <%= link_to "Login" , new_user_session_path,  class: "nav-link" %>
          </li>
          <% end %>
        </ul>
        <ul class="nav nav-pills mx-auto justify-content-between my-d-none d-md-none" id="blockquotes-tab" role="tablist" style="width: 80%;">
          <li class="nav-item">
            <a class="nav-link active" id="blockquotes-left-tab-1" data-toggle="pill" href="#blockquotes-left-1" role="tab" aria-controls="blockquotes-left-1" aria-selected="true">
              TOEIC
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="blockquotes-center-tab-1" data-toggle="pill" href="#blockquotes-center-1" role="tab" aria-controls="blockquotes-center-1" aria-selected="false">
              論文
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="blockquotes-right-tab-1" data-toggle="pill" href="#blockquotes-right-1" role="tab" aria-controls="blockquotes-right-1" aria-selected="false">
              小説
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
</header>
<!-- End Header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-EYPL6ZSL00"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-EYPL6ZSL00');
        </script>
        <%= display_meta_tags default_meta_tags %>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <!-- Web Fonts -->
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
        <link href="//fonts.googleapis.com/css?family=Playfair+Display:400,700%7COpen+Sans:300,400,700" rel="stylesheet">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= include_gon %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <!-- Demo Custome Code (demo page only) -->
        <style>
            type="text/css"/* Button Spaces*/
            .demo-btn-space .btn,
            .demo-progress-space .progress {
                margin-bottom: 10px;
            }

            /* About Section */
            .demo-about-section {
                position: relative;
                padding-top: 6.25rem;
            }

            @media(min-width: 991px) {
                .demo-about-section {
                    margin-top: -50px;
                    padding-top: 0;
                }
            }

            /* Download Section */
            .demo-download-section {
                position: relative;
                z-index: 1;
                margin: -60px 0;
            }

            /* Google Fonts */
            .demo-fonts-box {
                padding: 30px;
                line-height: 2;
                letter-spacing: 2px;
            }

            .demo-fonts-box__item {
                line-height: 1;
            }

            .demo-fonts-box__item-xs {
                line-height: 1;
                font-size: 30px;
            }

            .demo-fonts-box__item-xl {
                line-height: 1;
                font-size: 90px;
            }

            .nav-link {
                color: rgba(255, 255, 255, 0.9);
            }

            .nav-link:hover {
                color: rgba(255, 255, 255, 1);
            }
        </style>
    </head>

    <body>
        <%= render :partial => "layouts/header" %>
        <%= yield %>
    </body>

</html>